"""Calculates the Frechet Radiomics Distance (FRD) to compare image biomarker distributions.

The FRD metric calculates the distance between two distributions of biomarkers extracted from imaging data.
Typically, one of the two distributions is generated by a generative model such as GANs or Diffusion models.
When run as a stand-alone program, it compares the distribution of images that are stored as PNG/JPEG/NIfTI at
a specified location.

This implementation supports two versions of FRD:
  - FRDv0 (Osuala et al., 2024): ~94 radiomic features, min-max normalization, raw Fréchet distance.
  - FRDv1 (Konz, Osuala et al., 2026): ~464 radiomic features (including wavelet/LoG filters), z-score
    normalization w.r.t. D1, log-transformed Fréchet distance. Default version.

Reference: Konz, Osuala, et al. "Fréchet Radiomic Distance (FRD): A Versatile Metric for Comparing
Medical Imaging Datasets." Medical Image Analysis, 103943 (2026). https://arxiv.org/abs/2412.01496

Some code from https://github.com/mseitzer/pytorch-fid and https://github.com/bioinf-jku/TTUR was reused and adapted.

Usage:
    python -m frd_score dir1 dir2 [--frd_version v1]
"""

import argparse
import csv
import logging
import multiprocessing as mp
import os
import pathlib
import time
import warnings
from functools import partial
from pathlib import Path

import cv2
import numpy as np
from scipy import linalg

# pyradiomics is imported lazily so that `import frd_score` works even when
# pyradiomics is not installed (e.g. in the conda-forge build environment).
# The actual import is deferred to the first function call that needs it.
featureextractor = None  # set by _ensure_radiomics()
setVerbosity = None  # set by _ensure_radiomics()

_PYRADIOMICS_INSTALL_MSG = (
    "pyradiomics is not installed or failed to import.  "
    "The PyPI release (<=3.1.0) is broken for Python >=3.10.  "
    "Install from the GitHub master branch instead:\n\n"
    "  pip install git+https://github.com/AIM-Harvard/pyradiomics.git@master\n\n"
    "See: https://github.com/AIM-Harvard/pyradiomics/issues/903"
)


def _ensure_radiomics():
    """Lazily import pyradiomics on first use, raising a clear error if missing."""
    global featureextractor, setVerbosity
    if featureextractor is not None:
        return
    try:
        from radiomics import featureextractor as _fe
        from radiomics import setVerbosity as _sv
    except ImportError as exc:
        raise ImportError(_PYRADIOMICS_INSTALL_MSG) from exc
    featureextractor = _fe
    setVerbosity = _sv


import SimpleITK as sitk

try:
    from sklearn.manifold import TSNE

    _HAS_SKLEARN = True
except ImportError:
    _HAS_SKLEARN = False

try:
    import matplotlib

    matplotlib.use("Agg")  # non-interactive backend
    import matplotlib.pyplot as plt

    _HAS_MATPLOTLIB = True
except ImportError:
    _HAS_MATPLOTLIB = False


# Define allowed image extensions
IMAGE_EXTENSIONS = {
    "bmp",
    "jpg",
    "jpeg",
    "png",
    "tif",
    "tiff",
    "nii.gz",
}

# ─── FRD version constants ─────────────────────────────────────────────────────

FRD_VERSION_V0 = "v0"
FRD_VERSION_V1 = "v1"
FRD_VERSIONS = {FRD_VERSION_V0, FRD_VERSION_V1}
FRD_VERSION_DEFAULT = FRD_VERSION_V1

# ─── v0 default settings ───────────────────────────────────────────────────────
# correctMask: Resize mask if there is a size mismatch between image and mask
# minimumROIDimensions: Min number of dimensions for a ROI mask to avoid error.
# https://pyradiomics.readthedocs.io/en/latest/radiomics.html#radiomics.imageoperations.checkMask

V0_RADIOMICS_SETTINGS = {
    "correctMask": True,
    "minimumROIDimensions": 1,
}

V0_DEFAULT_FEATURES = [
    "firstorder",
    "glcm",
    "glrlm",
    "gldm",
    "glszm",
    "ngtdm",
    "shape",
    "shape2D",
]

V0_DEFAULT_NORM_TYPE = "minmax"
V0_DEFAULT_NORM_RANGE = [0.0, 7.45670747756958]

# ─── v1 default settings ───────────────────────────────────────────────────────
# v1 uses YAML-configured PyRadiomics with Extended feature extraction
# (Original + LoG + Wavelet filter images), resulting in ~464 features.
# Normalization is done via z-score w.r.t. the first (reference) distribution.
# Final FRD is log-transformed for stability.

V1_DEFAULT_NORM_TYPE = "zscore"
V1_DEFAULT_NORM_RANGE = [0.0, 1.0]

# ─── Image type defaults ──────────────────────────────────────────────────────
# PyRadiomics "image types" are the filter images from which features are extracted.
# v0 uses only Original; v1 adds LoG (Laplacian of Gaussian) and Wavelet.
# These can be overridden via --image_types for either version.

V0_DEFAULT_IMAGE_TYPES = ["Original"]
V1_DEFAULT_IMAGE_TYPES = ["Original", "LoG", "Wavelet"]
V1_DEFAULT_LOG_SIGMA = [2.0, 3.0, 4.0, 5.0]

# ─── PyRadiomics extraction defaults ──────────────────────────────────────────
# These can be overridden via the corresponding CLI flags or API parameters.

DEFAULT_BIN_WIDTH = 5
DEFAULT_NORMALIZE_SCALE = 100
DEFAULT_VOXEL_ARRAY_SHIFT = 300

# ─── Post-extraction feature exclusion ────────────────────────────────────────
# v1 supported excluding entire feature categories after extraction for ablation.

EXCLUDE_TEXTURAL = "textural"
EXCLUDE_WAVELET = "wavelet"
EXCLUDE_FIRSTORDER = "firstorder"
EXCLUDE_SHAPE = "shape"
EXCLUDE_OPTIONS = {EXCLUDE_TEXTURAL, EXCLUDE_WAVELET, EXCLUDE_FIRSTORDER, EXCLUDE_SHAPE}

# ─── Normalization reference mode ──────────────────────────────────────────────
# Controls which distribution's statistics are used as the normalization base.

NORM_REF_JOINT = "joint"  # Concatenate D1∪D2, normalize against joint stats
NORM_REF_D1 = "d1"  # Normalize both D1 and D2 using D1's statistics only
NORM_REF_INDEPENDENT = (
    "independent"  # Each set normalized using only its own statistics
)

# Version-specific defaults:
# v0 default: 'joint' — matches original v0's norm_sets_separately=True behavior
# v1 default: 'd1' — matches original v1's D1-only normalization (paper Eq. 3)
V0_DEFAULT_NORM_REF = NORM_REF_JOINT
V1_DEFAULT_NORM_REF = NORM_REF_D1
NORM_REF_DEFAULT = (
    None  # None means 'use version default'; resolved in _resolve_defaults()
)
NORM_REF_OPTIONS = {NORM_REF_JOINT, NORM_REF_D1, NORM_REF_INDEPENDENT}

# ─── Config paths (for v1 YAML-based extraction) ─────────────────────────────

_PACKAGE_DIR = os.path.dirname(os.path.abspath(__file__))
V1_CONFIG_2D = os.path.join(_PACKAGE_DIR, "configs", "extraction_2d.yaml")
V1_CONFIG_3D = os.path.join(_PACKAGE_DIR, "configs", "extraction_3d.yaml")


# ─────────────────────────────────────────────────────────────────────────────
#  CLI argument parsing
# ─────────────────────────────────────────────────────────────────────────────


def _add_shared_extraction_args(parser):
    """Add CLI arguments shared between the main FRD command and subcommands (OOD, etc.).

    These control feature extraction, normalization, and processing —
    common to any workflow that computes radiomics from image folders.
    """
    parser.add_argument(
        "--frd_version",
        type=str,
        default=FRD_VERSION_DEFAULT,
        choices=sorted(FRD_VERSIONS),
        help="The FRD version to use. 'v0' uses ~94 basic radiomic features and min-max "
        "normalization. 'v1' (default) uses ~464 features including wavelet/LoG filters, "
        "z-score normalization, and log-transformed Frechet distance.",
    )

    parser.add_argument(
        "-m",
        "--paths_masks",
        type=str,
        nargs=2,
        default=None,
        help="The two paths to the folders where the mask files are located.",
    )

    parser.add_argument(
        "-f",
        "--feature_groups",
        nargs="+",
        type=str,
        default=None,
        help="The pyradiomics feature classes to extract. Works for both v0 and v1. "
        "Can be 'firstorder', 'glcm', 'glrlm', 'gldm', 'glszm', 'ngtdm', 'shape', 'shape2D'. "
        "For v0: defaults to all of the above. "
        "For v1: defaults to the YAML-configured classes (firstorder, glcm, glrlm, glszm, ngtdm); "
        "specifying this overrides the YAML selection.",
    )

    parser.add_argument(
        "-I",
        "--image_types",
        nargs="+",
        type=str,
        default=None,
        help="The pyradiomics image types (filter images) from which features are extracted. "
        "Works for both v0 and v1. Common types: 'Original', 'LoG', 'Wavelet'. "
        "For v0: defaults to ['Original']. "
        "For v1: defaults to ['Original', 'LoG', 'Wavelet']. "
        "Specifying this overrides the version defaults. "
        "LoG uses sigma values from --log_sigma (default: [2.0, 3.0, 4.0, 5.0]).",
    )

    parser.add_argument(
        "-r",
        "--resize_size",
        type=int,
        nargs="+",
        default=None,
        help="Resize target for input images (and masks). "
        "A single int resizes to (N, N). Two ints resize to (W, H).",
    )

    parser.add_argument(
        "-R",
        "--norm_range",
        nargs=2,
        type=float,
        default=None,
        help="The allowed value range of features after normalization. Default depends on frd_version: "
        "v0=[0, 7.456], v1=[0, 1].",
    )

    parser.add_argument(
        "-T",
        "--norm_type",
        type=str,
        default=None,
        help="The normalization strategy. Default depends on frd_version: v0='minmax', v1='zscore'.",
    )

    parser.add_argument(
        "--norm_ref",
        type=str,
        default=NORM_REF_DEFAULT,
        choices=sorted(NORM_REF_OPTIONS),
        help="Controls the reference distribution used for feature normalization. "
        "Default depends on version: v0 defaults to 'joint', v1 defaults to 'd1'. "
        "'joint': features from both datasets are concatenated and used as the "
        "normalization base. "
        "'d1': both datasets are normalized using statistics from the first (reference) "
        "distribution only, as described in the FRD paper (Eq. 3). "
        "'independent': each dataset is normalized using only its own statistics. "
        "WARNING: 'independent' normalization may reduce comparability of FRD values.",
    )

    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable more detailed logging console logs.",
    )

    parser.add_argument(
        "-w",
        "--num_workers",
        type=int,
        default=None,
        help="The number of cpu workers for multiprocessing during feature extraction. "
        "If not set, the system's available cpu cores minus 2 will be used.",
    )

    parser.add_argument(
        "--log_sigma",
        nargs="+",
        type=float,
        default=None,
        help="Sigma values for the Laplacian of Gaussian (LoG) filter. "
        "Default: [2.0, 3.0, 4.0, 5.0] from the FRD paper. "
        "Only used when 'LoG' is in image_types.",
    )

    parser.add_argument(
        "--bin_width",
        type=int,
        default=None,
        help="Bin width for PyRadiomics feature discretization. "
        "Default: 5. Affects texture features significantly.",
    )

    parser.add_argument(
        "--config_path",
        type=str,
        default=None,
        help="Path to a custom PyRadiomics YAML configuration file. "
        "When provided, this overrides the built-in v1 YAML configs and "
        "takes precedence over --feature_groups, --image_types, --log_sigma, "
        "--bin_width, and PyRadiomics settings flags. "
        "Has no effect on v0 (which uses dict-based configuration).",
    )

    parser.add_argument(
        "--exclude_features",
        type=str,
        nargs="+",
        default=None,
        choices=sorted(EXCLUDE_OPTIONS),
        help="Post-extraction feature exclusion for ablation studies. "
        "Removes features matching the specified category *after* extraction. "
        "Options: 'textural' (glcm/glrlm/glszm/ngtdm/gldm), 'wavelet', 'firstorder', "
        "'shape' (shape/shape2D — often constant when no mask is used).",
    )

    parser.add_argument(
        "--match_sample_count",
        action="store_true",
        help="Randomly subsample the larger dataset to match the smaller dataset's size "
        "before computing statistics. Useful when dataset sizes differ substantially.",
    )

    parser.add_argument(
        "--normalize_scale",
        type=float,
        default=None,
        help="PyRadiomics internal normalization scale (default: 100). "
        "Controls the target scale for PyRadiomics' internal z-score normalization "
        "of image intensities before feature extraction.",
    )

    parser.add_argument(
        "--voxel_array_shift",
        type=float,
        default=None,
        help="PyRadiomics voxelArrayShift setting (default: 300). "
        "Added to image array to prevent negative values in firstorder features.",
    )


def _build_ood_parser(subparsers):
    """Add the ``ood`` subcommand to *subparsers* and return the sub-parser."""
    ood_parser = subparsers.add_parser(
        "ood",
        help="Out-of-distribution detection using radiomics features. "
        "Computes per-image OOD scores (L2 from reference mean) or "
        "dataset-level nFRD (AUC deviation).",
    )
    ood_parser.add_argument(
        "paths",
        type=str,
        nargs=2,
        help="Reference (in-distribution) image folder, then test image folder.",
    )
    # OOD-specific arguments
    ood_parser.add_argument(
        "--detection_type",
        type=str,
        default="image",
        choices=["image", "dataset"],
        help="'image': per-image OOD scoring with p-values. "
        "'dataset': dataset-level nFRD (AUC deviation) score.",
    )
    ood_parser.add_argument(
        "--val_frac",
        type=float,
        default=0.1,
        help="Fraction of reference images to hold out for threshold estimation (default: 0.1).",
    )
    ood_parser.add_argument(
        "--use_val_set",
        action="store_true",
        help="Use a held-out validation split for threshold estimation. "
        "By default (when not set), the full reference set is used for both "
        "the mean embedding and the threshold estimation (no hold-out split). "
        "Enabling this uses val_frac of the reference for threshold estimation only.",
    )
    ood_parser.add_argument(
        "--id_dist_assumption",
        type=str,
        default="gaussian",
        choices=["gaussian", "t", "counting"],
        help="Statistical distribution assumption for ID scores (default: gaussian).",
    )
    ood_parser.add_argument(
        "--output_dir",
        type=str,
        default="outputs/ood_predictions",
        help="Directory for OOD prediction CSV output.",
    )
    ood_parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Random seed for reproducibility of val split and sample matching. "
        "Original v1 used 1338.",
    )
    # Add all shared extraction/normalization arguments to the OOD subparser
    _add_shared_extraction_args(ood_parser)
    return ood_parser


def _add_frd_specific_args(parser):
    """Add arguments that are only relevant to the main FRD computation."""
    parser.add_argument(
        "paths",
        type=str,
        nargs=2,
        help="The two paths to the generated images or to .npz statistic files",
    )

    # Add shared extraction/normalization arguments to the main parser
    _add_shared_extraction_args(parser)

    parser.add_argument(
        "-s",
        "--save_stats",
        action="store_true",
        help="Generate an npz archive from a directory of samples. The first path is used as input and "
        "the second as output.",
    )

    parser.add_argument(
        "-F",
        "--save_features",
        action="store_true",
        help="Save radiomics feature values (normalized and non-normalized) in a csv file.",
    )

    parser.add_argument(
        "--use_paper_log",
        action="store_true",
        help="Use the log-transform formula as defined in the FRD paper (Eq. 3): "
        "FRD = log(d_F), where d_F = sqrt(d_F^2) is the non-squared Frechet distance. "
        "By default, FRDv1 uses the original code convention: FRD = log(d_F^2), which "
        "differs from the paper by a factor of 2. Enabling this flag produces FRD "
        "values consistent with the paper formula but NOT comparable to previously "
        "published FRD values computed with the default setting. "
        "Has no effect on v0 (which never applies a log transform).",
    )

    parser.add_argument(
        "--means_only",
        action="store_true",
        help="Compute mean-only Frechet distance (no covariance term). "
        "Useful for small datasets where covariance estimation is unreliable.",
    )

    parser.add_argument(
        "--interpret",
        action="store_true",
        help="Run interpretability analysis after computing FRD. "
        "Produces t-SNE visualizations and per-feature/per-image difference plots. "
        "Requires matplotlib and scikit-learn.",
    )

    parser.add_argument(
        "--interpret_dir",
        type=str,
        default="outputs/interpretability_visualizations",
        help="Output directory for interpretability visualizations (default: outputs/interpretability_visualizations).",
    )


# Known subcommands for the pre-parse peek (see parse_args).
_SUBCOMMANDS = frozenset({"ood"})


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments.

    argparse cannot reliably mix top-level positional arguments with
    ``add_subparsers``: it greedily tries to match the first positional
    token against subcommand names, so a plain path like ``/data/d1``
    fails with *"invalid choice"*.

    To work around this we peek at ``sys.argv`` to decide which parsing
    strategy to use **before** building the parser:

    * If the first positional token is a known subcommand (e.g. ``ood``),
      the parser is built with subparsers.
    * Otherwise the parser is built for the default FRD-compute mode
      (positional ``paths`` on the root parser, no subparsers).
    """
    import sys

    from . import __version__

    # --- Peek at argv to decide parsing strategy ----------------------------
    # Find the first token that is not a flag (starts with '-') and is not
    # the sentinel '--'.  Because some flags consume a following value
    # (e.g. --resize_size 64), the detected token may actually be a flag's
    # value rather than the true first positional argument — but that value
    # can never equal a subcommand name, so the logic stays correct.
    _first_pos = None
    for _a in sys.argv[1:]:
        if _a == "--":
            break
        if not _a.startswith("-"):
            _first_pos = _a
            break
    _use_subcommand = _first_pos in _SUBCOMMANDS

    # --- Build the appropriate parser --------------------------------------
    _epilog = (
        "subcommands:\n"
        "  ood         Out-of-distribution detection "
        "(run `%(prog)s ood --help` for details)"
    )

    parser = argparse.ArgumentParser(
        description="Calculates the Frechet Radiomics Distance between two "
        "distributions of extracted pyradiomics features.",
        epilog=_epilog,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )

    if _use_subcommand:
        subparsers = parser.add_subparsers(dest="subcommand")
        _build_ood_parser(subparsers)
    else:
        _add_frd_specific_args(parser)

    args = parser.parse_args()

    # Normalize resize_size: single int or (w, h) tuple
    if args.resize_size is not None:
        if len(args.resize_size) == 1:
            args.resize_size = args.resize_size[0]
        elif len(args.resize_size) == 2:
            args.resize_size = tuple(args.resize_size)
        else:
            parser.error(
                "--resize_size accepts 1 value (square) or 2 values (width height)."
            )

    return args


# ─────────────────────────────────────────────────────────────────────────────
#  Image utilities
# ─────────────────────────────────────────────────────────────────────────────


def resize_image_array(sitk_image_array, resize_size, interpolation=cv2.INTER_LINEAR):
    """Resize a 2D or 3D numpy array in the spatial dims.

    resize_size can be an int (square) or a (width, height) tuple.
    """
    if isinstance(resize_size, (list, tuple)):
        target_w, target_h = resize_size
    else:
        target_w, target_h = resize_size, resize_size

    if len(sitk_image_array.shape) == 2:
        sitk_image_array_resized = cv2.resize(
            sitk_image_array, (target_w, target_h), interpolation=interpolation
        )
    elif len(sitk_image_array.shape) == 3:
        # Going through z axis (index 0 in sitk array) and resizing each slice
        sitk_image_array_resized = np.zeros(
            (sitk_image_array.shape[0], target_h, target_w)
        )
        for j in range(sitk_image_array.shape[0]):
            sitk_image_array_resized[j] = cv2.resize(
                sitk_image_array[j],
                (target_w, target_h),
                interpolation=interpolation,
            )
    else:
        raise ValueError(
            f"SITK Image array has an unexpected shape: {sitk_image_array.shape}. "
            f"Expected 2D or 3D array (no channel dim). Got {len(sitk_image_array.shape)}D"
        )
    return sitk_image_array_resized


def _detect_image_dimensionality(files):
    """Detect whether the input images are 2D or 3D by reading the first file.

    Returns:
        int: 2 for 2D images, 3 for 3D images.
    """
    first_file = files[0] if not isinstance(files[0], list) else files[0][0]
    sitk_image = sitk.ReadImage(str(first_file), outputPixelType=sitk.sitkFloat32)
    ndim = sitk_image.GetDimension()
    arr = sitk.GetArrayViewFromImage(sitk_image)
    # SimpleITK adds a dimension for e.g. single-slice images
    # Use array shape to determine actual dimensionality
    if arr.ndim == 2 or (arr.ndim == 3 and arr.shape[0] == 1):
        return 2
    elif arr.ndim == 3 and arr.shape[0] > 1:
        return 3
    else:
        return ndim


# ─────────────────────────────────────────────────────────────────────────────
#  v0 feature extraction (settings-dict based)
# ─────────────────────────────────────────────────────────────────────────────


def get_feature_extractor_v0(features, settings_dict: dict = None):
    """Returns a pyradiomics feature extractor for v0.

    Constructs the extractor from a dict of feature class names and optional settings.
    """
    if isinstance(features, str) and features.endswith(".csv"):
        raise NotImplementedError(
            "Feature extraction based on a csv file is not yet implemented. "
            "Please open an issue: https://github.com/RichardObi/frd/issues/new/choose."
        )

    settings = {}
    if settings_dict is None:
        settings_dict = V0_RADIOMICS_SETTINGS
    settings["setting"] = settings_dict

    # Set feature classes to compute
    settings["featureClass"] = {feature: [] for feature in features}
    _ensure_radiomics()
    return featureextractor.RadiomicsFeatureExtractor(settings)


# ─────────────────────────────────────────────────────────────────────────────
#  v1 feature extraction (YAML-config based)
# ─────────────────────────────────────────────────────────────────────────────


def get_feature_extractor_v1(config_path: str):
    """Returns a pyradiomics feature extractor for v1, configured via a YAML file.

    The YAML config enables extended feature spaces (Original, LoG, Wavelet)
    and additional pyradiomics settings (normalization, resampling, etc.).
    """
    if not os.path.exists(config_path):
        raise FileNotFoundError(
            f"v1 YAML config not found at {config_path}. "
            "Please ensure the package is installed correctly."
        )
    _ensure_radiomics()
    return featureextractor.RadiomicsFeatureExtractor(config_path)


# ─────────────────────────────────────────────────────────────────────────────
#  Unified feature extractor factory
# ─────────────────────────────────────────────────────────────────────────────


def get_feature_extractor(
    frd_version: str = FRD_VERSION_DEFAULT,
    features=None,
    settings_dict: dict = None,
    image_dim: int = 2,
    image_types=None,
    log_sigma=None,
    config_path=None,
    bin_width=None,
    normalize_scale=None,
    voxel_array_shift=None,
):
    """Factory function that returns the appropriate pyradiomics feature extractor.

    After creating the base extractor (dict-based for v0, YAML-based for v1),
    unified overrides for feature classes and image types are applied.

    Params:
    -- frd_version      : 'v0' or 'v1'
    -- features         : list of feature class names to extract. For v0, defaults to
                          V0_DEFAULT_FEATURES. For v1, None means use YAML defaults;
                          if specified, overrides the YAML feature classes.
    -- settings_dict    : (v0 only) optional radiomics settings dict override
    -- image_dim        : 2 or 3, used to pick the correct YAML config in v1 mode
    -- image_types      : list of image type names (e.g. ['Original', 'LoG', 'Wavelet']).
                          None means use version defaults. If specified, overrides
                          the image types for either version.
    -- log_sigma        : list of float sigma values for LoG filter.
                          None means use V1_DEFAULT_LOG_SIGMA.
    -- config_path      : path to a custom PyRadiomics YAML config (v1 only).
                          When provided, overrides the built-in YAML configs.
    -- bin_width        : int, PyRadiomics binWidth setting override.
    -- normalize_scale  : float, PyRadiomics normalizeScale setting override.
    -- voxel_array_shift: float, PyRadiomics voxelArrayShift setting override.

    Returns:
    -- A RadiomicsFeatureExtractor instance.
    """
    if log_sigma is None:
        log_sigma = list(V1_DEFAULT_LOG_SIGMA)

    if frd_version == FRD_VERSION_V0:
        if features is None:
            features = V0_DEFAULT_FEATURES
        extractor = get_feature_extractor_v0(features, settings_dict)
    elif frd_version == FRD_VERSION_V1:
        if config_path is not None:
            extractor = get_feature_extractor_v1(config_path)
        else:
            _config_path = V1_CONFIG_2D if image_dim == 2 else V1_CONFIG_3D
            extractor = get_feature_extractor_v1(_config_path)
        # For v1, apply feature class override if user explicitly specified feature_groups
        if features is not None and config_path is None:
            desired = set(features)
            # Snapshot YAML-configured features (value is list or None=all)
            yaml_features = dict(extractor.enabledFeatures)
            extractor.disableAllFeatures()
            for cls_name in desired:
                if cls_name in yaml_features:
                    # Restore the YAML's specific feature selection for this class
                    # enableFeaturesByName takes **kwargs: className=[featureNames] or None=all
                    extractor.enableFeaturesByName(
                        **{cls_name: yaml_features[cls_name]}
                    )
                else:
                    # Class was not in the YAML config — enable all features in it
                    extractor.enableFeatureClassByName(cls_name)
    else:
        raise ValueError(
            f"Unknown frd_version '{frd_version}'. Must be one of {sorted(FRD_VERSIONS)}."
        )

    # Apply image type override (works for both v0 and v1, skipped if config_path given)
    if image_types is not None and config_path is None:
        extractor.disableAllImageTypes()
        for img_type in image_types:
            if img_type == "LoG":
                extractor.enableImageTypeByName("LoG", customArgs={"sigma": log_sigma})
            else:
                extractor.enableImageTypeByName(img_type)
    elif config_path is None:
        # Even without an image_types override, apply log_sigma if LoG is enabled
        # (user may have supplied --log_sigma without --image_types)
        enabled_types = extractor.enabledImagetypes
        if "LoG" in enabled_types:
            extractor.enableImageTypeByName("LoG", customArgs={"sigma": log_sigma})

    # Apply PyRadiomics setting overrides
    if bin_width is not None and config_path is None:
        extractor.settings["binWidth"] = bin_width
    if normalize_scale is not None and config_path is None:
        extractor.settings["normalizeScale"] = normalize_scale
    if voxel_array_shift is not None and config_path is None:
        extractor.settings["voxelArrayShift"] = voxel_array_shift

    return extractor


# ─────────────────────────────────────────────────────────────────────────────
#  Per-image feature extraction
# ─────────────────────────────────────────────────────────────────────────────


def process_image_mask_pair(
    image_mask_pair,
    resize_size=None,
    feature_extractor=None,
    verbose=False,
    frd_version=FRD_VERSION_DEFAULT,
):
    """Extract radiomics features from an (image, mask) pair.

    Returns a tuple of (feature_values_list, feature_dict, num_features) or None on failure.
    """
    image_path, mask_path = image_mask_pair

    sitk_image = sitk.ReadImage(str(image_path), outputPixelType=sitk.sitkFloat32)

    if mask_path is None:
        # Create full-image mask when no mask file is provided
        # https://discourse.slicer.org/t/features-extraction/11047/3
        ma_arr = np.ones(sitk_image.GetSize()[::-1]).astype(np.uint8)
        # Prevent pyradiomics bug: set corner voxel to 0
        # https://github.com/AIM-Harvard/pyradiomics/issues/765#issuecomment-1116713745
        # Only for v1 mode — original v0 did not apply this workaround.
        if frd_version != FRD_VERSION_V0:
            if ma_arr.ndim == 2:
                ma_arr[0][0] = 0
            elif ma_arr.ndim >= 3:
                ma_arr[0][0][0] = 0
        sitk_mask = sitk.GetImageFromArray(ma_arr)
        try:
            sitk_mask.CopyInformation(sitk_image)
        except Exception as e:
            logging.debug(
                f"Error while trying to copy information from image to mask: {e}"
            )
        if verbose:
            logging.debug(
                "Empty mask (true everywhere except corner) is used for feature extraction."
            )
    else:
        sitk_mask = sitk.ReadImage(str(mask_path))

    # Rescale [0, 255] masks to [0, 1]
    if np.max(sitk.GetArrayViewFromImage(sitk_mask)) == 255:
        sitk_mask = sitk.Cast(sitk_mask, sitk.sitkFloat32) / 255.0

    if resize_size is not None:
        sitk_image_array = sitk.GetArrayViewFromImage(sitk_image)
        sitk_image_array_resized = resize_image_array(
            sitk_image_array, resize_size, interpolation=cv2.INTER_LINEAR
        )
        sitk_image_resized = sitk.GetImageFromArray(sitk_image_array_resized)
        try:
            sitk_image_resized.CopyInformation(sitk_image)
        except Exception:
            pass
        sitk_image = sitk_image_resized

        sitk_mask_array = sitk.GetArrayViewFromImage(sitk_mask)
        sitk_mask_array_resized = resize_image_array(
            sitk_mask_array, resize_size, interpolation=cv2.INTER_LINEAR
        )
        # Threshold after resizing
        sitk_mask_array_resized[sitk_mask_array_resized > 0.5] = 1
        sitk_mask_array_resized[sitk_mask_array_resized <= 0.5] = 0
        sitk_mask_resized = sitk.GetImageFromArray(sitk_mask_array_resized)
        try:
            sitk_mask_resized.CopyInformation(sitk_mask)
        except Exception:
            pass
        sitk_mask = sitk_mask_resized

    # Skip masks with <=1 segmented voxel
    if np.sum(sitk.GetArrayViewFromImage(sitk_mask)) <= 1:
        if verbose:
            logging.warning(
                f"Skipping mask with ≤1 segmented voxel (resize_size={resize_size}): {mask_path}"
            )
        return None

    # Ensure 2D images are expanded to 3D (1, H, W) for v1 YAML configs
    # that require 3D resampledPixelSpacing with force2D=true.
    # Only for v1 mode — original v0 passes 2D images directly to pyradiomics.
    img_arr = sitk.GetArrayFromImage(sitk_image)
    if img_arr.ndim == 2 and frd_version != FRD_VERSION_V0:
        img_arr_3d = img_arr[np.newaxis, ...]
        sitk_image_3d = sitk.GetImageFromArray(img_arr_3d)
        # Preserve original spacing, add z-spacing of 1.0
        orig_spacing = sitk_image.GetSpacing()
        sitk_image_3d.SetSpacing((*orig_spacing, 1.0))
        sitk_image = sitk_image_3d

        mask_arr = sitk.GetArrayFromImage(sitk_mask)
        if mask_arr.ndim == 2:
            mask_arr_3d = mask_arr[np.newaxis, ...]
            sitk_mask_3d = sitk.GetImageFromArray(mask_arr_3d)
            sitk_mask_3d.SetSpacing((*orig_spacing, 1.0))
            sitk_mask = sitk_mask_3d

    # Run feature extraction
    try:
        output = feature_extractor.execute(sitk_image, sitk_mask)
    except Exception as e:
        logging.error(
            f"Error extracting features for image {image_path} / mask {mask_path}: {e}"
        )
        raise e

    radiomics_features = {}
    for feature_name in output.keys():
        if "diagnostics" not in feature_name:
            radiomics_features[feature_name.replace("original_", "")] = float(
                output[feature_name]
            )
        elif frd_version == FRD_VERSION_V1:
            # Original v1 stored all pyradiomics output in a DataFrame, then
            # dropped string-typed and shape2D columns.  Numeric diagnostics
            # (e.g. Image-original_Mean, Mask-original_VoxelNum) survived this
            # filter and were included in the feature vector used to compute FRD
            # in the paper.  We replicate this for exact paper reproducibility.
            try:
                val = float(output[feature_name])
                radiomics_features[feature_name] = val
            except (ValueError, TypeError):
                pass  # skip string diagnostics
    radiomics_feature_values_list = list(radiomics_features.values())

    return (
        radiomics_feature_values_list,
        radiomics_features,
        len(radiomics_feature_values_list),
    )


# ─────────────────────────────────────────────────────────────────────────────
#  Batch feature extraction
# ─────────────────────────────────────────────────────────────────────────────


def compute_features(
    files,
    feature_extractor,
    masks=None,
    resize_size=None,
    verbose=False,
    num_workers=None,
    frd_version=FRD_VERSION_DEFAULT,
):
    """Compute radiomics features for a list of image files.

    Params:
    -- files              : Image file paths
    -- feature_extractor  : RadiomicsFeatureExtractor instance
    -- masks              : Corresponding mask file paths (or None for full-image masks)
    -- resize_size        : Optional resize target
    -- verbose            : Logging verbosity
    -- num_workers        : CPU workers for multiprocessing (None = auto)
    -- frd_version        : 'v0' or 'v1', controls image preprocessing behavior

    Returns:
    -- pred_arr             : np.ndarray of shape (num_images, num_features)
    -- radiomics_dicts_list : list of feature name->value dicts
    -- mask_paths           : list of mask paths used
    """
    mask_paths = []
    for idx, file_path in enumerate(files):
        if masks is not None:
            try:
                mask_paths.append(masks[idx])
            except IndexError as e:
                raise RuntimeError(
                    f"Mask '{idx}' not found for image '{file_path}'. "
                    f"Ensure each image has a mask and names correspond via sorting. "
                    f"Exception: {e}"
                )
        else:
            mask_paths.append(None)

    if verbose:
        logging.info(
            f"Processing {len(files)} image-mask pairs (e.g., IMG[0]:{files[0]}, MASK[0]: {mask_paths[0]})"
        )

    # Multiprocessing
    if num_workers is None:
        num_workers = max(1, mp.cpu_count() - 2)
    if num_workers < 1:
        num_workers = 1
    process_pairs = partial(
        process_image_mask_pair,
        resize_size=resize_size,
        feature_extractor=feature_extractor,
        verbose=verbose,
        frd_version=frd_version,
    )
    with mp.Pool(processes=num_workers) as p:
        results = p.map(process_pairs, zip(files, mask_paths))

    features_list = []
    list_radiomics_feature_dict_list = []

    for i, result in enumerate(results):
        if result is None:
            logging.warning(f"Feature extraction skipped for image {files[i]}")
            continue
        features_list.append(result[0])
        list_radiomics_feature_dict_list.append(result[1])

    if not features_list:
        raise RuntimeError("No features could be extracted from any image.")

    if verbose:
        logging.info(f"Number of radiomics features: {len(features_list[0])}")

    pred_arr = np.asarray(features_list)
    return pred_arr, list_radiomics_feature_dict_list, mask_paths


# ─────────────────────────────────────────────────────────────────────────────
#  CSV save
# ─────────────────────────────────────────────────────────────────────────────


def save_features_to_csv(csv_file_path, image_paths, mask_paths, feature_data):
    """Save extracted feature data to a CSV file."""
    with open(csv_file_path, "w", newline="") as csv_file:
        writer = csv.writer(csv_file)

        header = ["image_path", "mask_path"]
        for feature_name in feature_data[0].keys():
            header.append(feature_name)
        writer.writerow(header)

        for image_path, mask_path, features in zip(
            image_paths, mask_paths, feature_data
        ):
            row = [str(image_path), str(mask_path)]
            row.extend(features.values())
            writer.writerow(row)

        num_features = len(feature_data[0])
        min_values = [
            np.min([data[feature_name] for data in feature_data])
            for feature_name in feature_data[0].keys()
        ]
        max_values = [
            np.max([data[feature_name] for data in feature_data])
            for feature_name in feature_data[0].keys()
        ]
        empty_row = [""] * (num_features + 2)
        writer.writerow(empty_row)
        writer.writerow(["Min", ""] + min_values)
        writer.writerow(empty_row)
        writer.writerow(["Max", ""] + max_values)
    logging.info(f"Feature data saved to {csv_file_path}.")


# ─────────────────────────────────────────────────────────────────────────────
#  Frechet distance
# ─────────────────────────────────────────────────────────────────────────────


def calculate_frechet_distance(mu1, sigma1, mu2, sigma2, eps=1e-6, means_only=False):
    """Numpy implementation of the Frechet Distance.

    d^2 = ||mu_1 - mu_2||^2 + Tr(C_1 + C_2 - 2*sqrt(C_1*C_2)).

    If means_only=True, only the mean term is computed (no covariance).
    Stable version by Dougal J. Sutherland.
    """
    mu1 = np.atleast_1d(mu1)
    mu2 = np.atleast_1d(mu2)

    diff = mu1 - mu2

    if means_only:
        return float(diff.dot(diff))

    sigma1 = np.atleast_2d(sigma1)
    sigma2 = np.atleast_2d(sigma2)

    assert (
        mu1.shape == mu2.shape
    ), "Dataset1 and dataset2 mean vectors have different lengths"
    assert (
        sigma1.shape == sigma2.shape
    ), "Dataset1 and dataset2 covariances have different dimensions"

    diff = mu1 - mu2

    # Product might be almost singular
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        covmean = linalg.sqrtm(sigma1.dot(sigma2))
    if not np.isfinite(covmean).all():
        msg = (
            "Frechet distance produces singular product; "
            "adding %s to diagonal of cov estimates"
        ) % eps
        logging.debug(msg)
        offset = np.eye(sigma1.shape[0]) * eps
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            covmean = linalg.sqrtm((sigma1 + offset).dot(sigma2 + offset))

    # Numerical error might give slight imaginary component
    if np.iscomplexobj(covmean):
        if not np.allclose(np.diagonal(covmean).imag, 0, atol=1e-3):
            m = np.max(np.abs(covmean.imag))
            logging.debug(f"Imaginary component in covmean: {m}")
        covmean = covmean.real

    tr_covmean = np.trace(covmean)
    return diff.dot(diff) + np.trace(sigma1) + np.trace(sigma2) - 2 * tr_covmean


# ─────────────────────────────────────────────────────────────────────────────
#  Normalization utilities
# ─────────────────────────────────────────────────────────────────────────────


def z_score_normalize(
    features,
    new_min=0,
    new_max=1,
    replace_nan=True,
    strict=False,
    feature_names=None,
    base_distribution=None,
    handle_std_zero=True,
):
    """Z-score normalize features and rescale to [new_min, new_max].

    If base_distribution is provided, mean/std are computed from it (used for
    joint normalization across both datasets).

    Params:
    -- handle_std_zero : bool.  When True (default), features with std=0 are
           set to ``new_min``.  When False, the raw division-by-zero is kept
           (producing inf), which mirrors the original v1 pipeline and lets
           the downstream NaN/Inf column filter handle these features.
    """
    mean_values = (
        np.nanmean(features, axis=0)
        if base_distribution is None
        else np.nanmean(base_distribution, axis=0)
    )
    std_values = (
        np.nanstd(features, axis=0)
        if base_distribution is None
        else np.nanstd(base_distribution, axis=0)
    )

    normalized_features = np.copy(features)

    for idx, (mean_val, std_val) in enumerate(zip(mean_values, std_values)):
        if not np.isnan(mean_val) and not np.isnan(std_val):
            feature_name = (
                feature_names[idx] if feature_names is not None else f"feature_{idx}"
            )
            logging.debug(f"{feature_name} std_val: {std_val}, mean_val: {mean_val}")
            if std_val == 0 and strict:
                raise ValueError(
                    f"z-score: std=0 for feature {feature_name} (mean={mean_val}). "
                    f"Set norm_type to 'minmax' to avoid this."
                )
            if std_val == 0 and handle_std_zero:
                logging.warning(
                    f"z-score: std=0 for feature {feature_name} (mean={mean_val}). "
                    f"Replacing with 0 + new_min={new_min}."
                )
                normalized_features[:, idx] = 0 + float(new_min)
            else:
                with np.errstate(divide="ignore", invalid="ignore"):
                    normalized_features[:, idx] = (
                        (features[:, idx] - mean_val) / std_val
                    ) * (float(new_max) - float(new_min)) + float(new_min)

    if replace_nan:
        nan_indices = np.isnan(normalized_features)
        mean_value = (float(new_min) + float(new_max)) / 2
        normalized_features[nan_indices] = mean_value

    return normalized_features


def min_max_normalize(
    features,
    new_min,
    new_max,
    replace_nan=True,
    feature_names=None,
    base_distribution=None,
):
    """Min-max normalize features and rescale to [new_min, new_max].

    If base_distribution is provided, min/max are computed from it.
    """
    min_values = (
        np.nanmin(features, axis=0)
        if base_distribution is None
        else np.nanmin(base_distribution, axis=0)
    )
    max_values = (
        np.nanmax(features, axis=0)
        if base_distribution is None
        else np.nanmax(base_distribution, axis=0)
    )

    normalized_features = np.copy(features)

    for idx, (min_val, max_val) in enumerate(zip(min_values, max_values)):
        if not np.isnan(min_val) and not np.isnan(max_val):
            if (max_val - min_val) == 0:
                feature_name = (
                    feature_names[idx]
                    if feature_names is not None
                    else f"feature_{idx}"
                )
                logging.info(
                    f"minmax: max-min=0 for feature {feature_name}. "
                    f"Replacing with 0.5 scaled to ({float(new_min)}, {float(new_max)})."
                )
                normalized_features[:, idx] = 0.5 * (
                    float(new_max) - float(new_min)
                ) + float(new_min)
            else:
                normalized_features[:, idx] = (
                    (features[:, idx] - min_val) / (max_val - min_val)
                ) * (float(new_max) - float(new_min)) + float(new_min)

    if replace_nan:
        nan_indices = np.isnan(normalized_features)
        mean_value = (new_min + new_max) / 2
        normalized_features[nan_indices] = mean_value

    return normalized_features


# ─────────────────────────────────────────────────────────────────────────────
#  Post-extraction feature filtering
# ─────────────────────────────────────────────────────────────────────────────


def _apply_exclude_features(feature_arrays, feature_names, exclude_features):
    """Remove features matching the specified categories from all arrays.

    Params:
    -- feature_arrays   : list of np.ndarray, each (n_samples, n_features)
    -- feature_names    : list of str, feature names corresponding to columns
    -- exclude_features : list of str from EXCLUDE_OPTIONS

    Returns:
    -- filtered_arrays : list of np.ndarray with excluded columns removed
    -- filtered_names  : list of str with excluded names removed
    """
    if not exclude_features:
        return feature_arrays, feature_names

    keep_mask = np.ones(len(feature_names), dtype=bool)

    for excl in exclude_features:
        if excl == EXCLUDE_TEXTURAL:
            # Texture features: glcm, glrlm, glszm, ngtdm, gldm
            for idx, name in enumerate(feature_names):
                parts = name.split("_")
                if len(parts) >= 2:
                    cls_part = parts[0].split("-")[-1] if "-" in parts[0] else parts[0]
                    if cls_part.startswith("gl") or cls_part == "ngtdm":
                        keep_mask[idx] = False
        elif excl == EXCLUDE_WAVELET:
            for idx, name in enumerate(feature_names):
                if name.startswith("wavelet"):
                    keep_mask[idx] = False
        elif excl == EXCLUDE_FIRSTORDER:
            for idx, name in enumerate(feature_names):
                if "firstorder" in name:
                    keep_mask[idx] = False
        elif excl == EXCLUDE_SHAPE:
            # Shape features: shape_* and shape2D_* (often constant without masks)
            # Also catches wavelet-prefixed variants like wavelet-LLH_shape_*
            for idx, name in enumerate(feature_names):
                parts = name.split("_")
                if len(parts) >= 2:
                    for p in parts[:-1]:
                        clean = p.split("-")[-1] if "-" in p else p
                        if clean == "shape" or clean == "shape2D":
                            keep_mask[idx] = False
                            break

    filtered_names = [n for n, k in zip(feature_names, keep_mask) if k]
    filtered_arrays = [arr[:, keep_mask] for arr in feature_arrays]

    n_removed = int(np.sum(~keep_mask))
    if n_removed > 0:
        logging.info(
            f"exclude_features={exclude_features}: removed {n_removed} features, "
            f"{len(filtered_names)} remaining."
        )

    return filtered_arrays, filtered_names


def _apply_match_sample_count(feature_list):
    """Subsample the larger dataset to match the smaller one.

    Params:
    -- feature_list : list of np.ndarray, each (n_samples, n_features)

    Returns:
    -- feature_list : list with the larger array randomly subsampled
    """
    if len(feature_list) != 2:
        return feature_list

    n0, n1 = feature_list[0].shape[0], feature_list[1].shape[0]
    if n0 > n1:
        indices = np.random.choice(n0, n1, replace=False)
        feature_list[0] = feature_list[0][indices]
        logging.info(f"match_sample_count: subsampled D1 from {n0} to {n1} samples.")
    elif n1 > n0:
        indices = np.random.choice(n1, n0, replace=False)
        feature_list[1] = feature_list[1][indices]
        logging.info(f"match_sample_count: subsampled D2 from {n1} to {n0} samples.")

    return feature_list


# ─────────────────────────────────────────────────────────────────────────────
#  Interpretability analysis
# ─────────────────────────────────────────────────────────────────────────────


def interpret_frd(
    feature_list,
    feature_names,
    viz_dir="outputs/interpretability_visualizations",
    run_tsne=True,
):
    """Run interpretability analysis on extracted radiomic features.

    Produces t-SNE visualizations and per-feature difference rankings.

    Params:
    -- feature_list  : list of two np.ndarray (n_samples, n_features), normalized features
    -- feature_names : list of str, feature names
    -- viz_dir       : output directory for visualizations
    -- run_tsne      : whether to run t-SNE embedding visualization

    Returns:
    -- dict with interpretation results (top_changed_features, etc.)
    """
    if not _HAS_MATPLOTLIB:
        raise ImportError(
            "Interpretability analysis requires matplotlib. "
            "Install with: pip install matplotlib"
        )

    os.makedirs(viz_dir, exist_ok=True)
    feats1, feats2 = feature_list[0], feature_list[1]
    results = {}

    # t-SNE visualization
    if run_tsne:
        if not _HAS_SKLEARN:
            warnings.warn(
                "t-SNE requires scikit-learn. Install with: pip install scikit-learn. "
                "Skipping t-SNE visualization.",
                UserWarning,
                stacklevel=2,
            )
        else:
            logging.info("Running t-SNE on radiomic features...")
            all_feats = np.concatenate([feats1, feats2], axis=0)
            emb = TSNE(
                n_components=2, perplexity=min(10, all_feats.shape[0] - 1), n_iter=1000
            ).fit_transform(all_feats)

            domain_labels = np.concatenate(
                [
                    np.zeros(feats1.shape[0]),
                    np.ones(feats2.shape[0]),
                ]
            )
            plt.figure(figsize=(6, 6), dpi=150)
            for label, name, color in [(0, "D1", "tab:blue"), (1, "D2", "tab:orange")]:
                mask = domain_labels == label
                plt.scatter(
                    emb[mask, 0], emb[mask, 1], label=name, alpha=0.5, c=color, s=20
                )
            plt.title("Radiomic Feature t-SNE")
            plt.legend()
            plt.tight_layout()
            tsne_path = os.path.join(viz_dir, "radiomic_tsne.png")
            plt.savefig(tsne_path, bbox_inches="tight")
            plt.close()
            logging.info(f"t-SNE plot saved to {tsne_path}")

    # Per-feature difference ranking (distribution-level)
    feature_names_arr = np.array(feature_names)
    mean_diff_sq = (np.mean(feats2, axis=0) - np.mean(feats1, axis=0)) ** 2
    sorted_idx = mean_diff_sq.argsort()[::-1]

    top_k = min(20, len(feature_names))
    top_features = [
        (feature_names_arr[i], float(mean_diff_sq[i])) for i in sorted_idx[:top_k]
    ]
    results["top_changed_features"] = top_features

    # Plot per-feature differences
    plt.figure(figsize=(5, 3), dpi=150)
    x = np.arange(len(mean_diff_sq))
    plt.plot(x, mean_diff_sq[sorted_idx], "-", color="indianred")
    plt.yscale("log")
    plt.title("Per-feature mean difference (sorted)")
    plt.xlabel("sorted feature index")
    plt.ylabel("$|\\Delta \\mu|^2$")
    plt.grid(True, alpha=0.3)
    feat_diff_path = os.path.join(viz_dir, "sorted_feature_differences.png")
    plt.savefig(feat_diff_path, bbox_inches="tight")
    plt.close()

    # Print top features
    print(f"\nTop {top_k} changed radiomic features:")
    for name, val in top_features:
        print(f"  {name}: {val:.4f}")

    results["n_features"] = len(feature_names)
    return results


# ─────────────────────────────────────────────────────────────────────────────
#  OOD detection
# ─────────────────────────────────────────────────────────────────────────────


def detect_ood(
    feature_list,
    detection_type="image",
    val_frac=0.1,
    use_val_set=False,
    id_dist_assumption="gaussian",
    output_dir="outputs/ood_predictions",
    seed=None,
    filenames=None,
):
    """Out-of-distribution detection using radiomics features.

    Params:
    -- feature_list       : list of two np.ndarray [D1_features, D2_features],
                            where D1 is in-distribution (reference) and D2 is test.
    -- detection_type     : 'image' for per-image scoring, 'dataset' for nFRD.
    -- val_frac           : fraction of D1 to hold out for threshold estimation.
    -- use_val_set        : if True, hold out val_frac of D1 for threshold estimation.
                            If False (default), use the full reference set for both
                            the mean embedding and threshold estimation (no split).
    -- id_dist_assumption : 'gaussian', 't', or 'counting' for threshold estimation.
    -- output_dir         : directory for saving OOD prediction CSVs.
    -- seed               : random seed for reproducibility (val split, sample matching).
    -- filenames          : list of filenames for the test set images (for CSV output).

    Returns:
    -- dict with results (scores, predictions, nfrd, etc.)
    """
    from scipy import stats as sps

    rng = np.random.default_rng(seed)

    feats_ref = feature_list[0]
    feats_test = feature_list[1]
    results = {}

    if use_val_set:
        # Split reference into train/val
        n_ref = feats_ref.shape[0]
        n_val = max(1, int(val_frac * n_ref))
        val_idx = rng.choice(n_ref, n_val, replace=False)
        train_idx = np.array([i for i in range(n_ref) if i not in val_idx])
        ref_train = feats_ref[train_idx]
        ref_val = feats_ref[val_idx]
    else:
        # No hold-out: use full reference for both mean and threshold estimation
        ref_train = feats_ref
        ref_val = feats_ref

    # Compute mean of reference training set
    ref_mean = ref_train.mean(axis=0)

    # L2 scores
    test_scores = np.array([np.linalg.norm(ref_mean - x) for x in feats_test])
    val_scores = np.array([np.linalg.norm(ref_mean - x) for x in ref_val])

    if detection_type == "image":
        mu_val, sigma_val = np.mean(val_scores), np.std(val_scores)
        dof = len(val_scores) - 1

        if id_dist_assumption == "gaussian":
            threshold = sigma_val * sps.norm.ppf(0.95) + mu_val
            z = (test_scores - mu_val) / max(sigma_val, 1e-10)
            p_values = 1 - sps.norm.cdf(z)
        elif id_dist_assumption == "t":
            threshold = sigma_val * sps.t.ppf(0.95, max(dof, 1)) + mu_val
            t_stat = (test_scores - mu_val) / max(
                sigma_val / np.sqrt(len(val_scores)), 1e-10
            )
            p_values = 1 - sps.t.cdf(t_stat, max(dof, 1))
        elif id_dist_assumption == "counting":
            threshold = np.percentile(val_scores, 95)
            p_values = np.array(
                [np.sum(val_scores > score) / len(val_scores) for score in test_scores]
            )
        else:
            raise ValueError(f"Unknown id_dist_assumption: {id_dist_assumption}")

        predictions = test_scores > threshold
        results["threshold"] = float(threshold)
        results["scores"] = test_scores
        results["predictions"] = predictions
        results["p_values"] = p_values

        # Save to CSV
        os.makedirs(output_dir, exist_ok=True)
        csv_path = os.path.join(output_dir, "ood_predictions.csv")
        with open(csv_path, "w", newline="") as f:
            writer = csv.writer(f)
            if filenames is not None:
                writer.writerow(["filename", "ood_score", "ood_prediction", "p_value"])
                for i in range(len(test_scores)):
                    fname = filenames[i] if i < len(filenames) else str(i)
                    writer.writerow(
                        [fname, test_scores[i], bool(predictions[i]), p_values[i]]
                    )
            else:
                writer.writerow(["index", "ood_score", "ood_prediction", "p_value"])
                for i in range(len(test_scores)):
                    writer.writerow(
                        [i, test_scores[i], bool(predictions[i]), p_values[i]]
                    )
        print(f"OOD predictions saved to {csv_path}")
        print(
            f"Threshold: {threshold:.4f}, OOD detected: {int(predictions.sum())}/{len(predictions)}"
        )

    elif detection_type == "dataset":
        try:
            from sklearn.metrics import roc_auc_score
        except ImportError:
            raise ImportError(
                "Dataset-level OOD detection requires scikit-learn. "
                "Install with: pip install scikit-learn"
            )

        all_scores = np.concatenate([val_scores, test_scores])
        all_labels = np.concatenate(
            [np.zeros(len(val_scores)), np.ones(len(test_scores))]
        )
        auc_dev = 2.0 * abs(roc_auc_score(all_labels, all_scores) - 0.5)
        results["nfrd"] = float(auc_dev)
        print(f"Dataset-level OOD score (nFRD): {auc_dev:.4f}")

    else:
        raise ValueError(
            f"detection_type must be 'image' or 'dataset', got '{detection_type}'."
        )

    return results


# ─────────────────────────────────────────────────────────────────────────────
#  Statistics calculation
# ─────────────────────────────────────────────────────────────────────────────


def calculate_feature_statistics(
    file_lists: list,
    norm_type: str,
    norm_range: list,
    feature_extractor,
    mask_lists: list = None,
    resize_size=None,
    verbose: bool = False,
    save_features: bool = False,
    norm_ref: str = NORM_REF_DEFAULT,
    num_workers=None,
    exclude_features=None,
    match_sample_count=False,
    frd_version=FRD_VERSION_DEFAULT,
):
    """Extract features and compute per-distribution statistics (mean, covariance).

    Params:
    -- exclude_features  : list of str from EXCLUDE_OPTIONS, feature categories to drop
    -- match_sample_count: bool, if True subsample larger set to match smaller

    Returns:
    -- mu_list                : List of mean vectors for each distribution.
    -- sigma_list             : List of covariance matrices for each distribution.
    -- normalized_feature_list: List of normalized feature arrays.
    -- feature_names          : List of feature name strings.
    """
    if mask_lists is None:
        mask_lists = [None] * len(file_lists)

    feature_list = []
    feature_names = []
    all_radiomics_results = []
    all_mask_paths = []

    for idx, file_list in enumerate(file_lists):
        features, radiomics_results, mask_paths = compute_features(
            files=file_list,
            feature_extractor=feature_extractor,
            masks=mask_lists[idx] if mask_lists is not None else None,
            resize_size=resize_size,
            verbose=verbose,
            num_workers=num_workers,
            frd_version=frd_version,
        )
        if verbose:
            logging.info(f"Features shape: {features.shape}")

        # Log NaN diagnostics
        if np.isnan(features).any():
            nan_indices = np.where(np.isnan(features))
            unique_nan_indices = np.unique(nan_indices[1])
            logging.warning("NaN values detected in features array.")
            if verbose:
                for feature_idx in unique_nan_indices:
                    nan_count = np.sum(np.isnan(features[:, feature_idx]))
                    logging.info(f"Feature {feature_idx}: {nan_count} NaN values")

        feature_list.append(features)
        feature_names = list(radiomics_results[0].keys())
        all_radiomics_results.append(radiomics_results)
        all_mask_paths.append(mask_paths)

    # ── Exclude feature categories ──
    if exclude_features:
        feature_list, feature_names = _apply_exclude_features(
            feature_list, feature_names, exclude_features
        )

    # ── v1-specific preprocessing (paper-exact pipeline) ──
    # The original v1 converted features to float32 (via pandas .to_numpy().astype(np.float32))
    # and dropped rows with any NaN (via pandas .dropna()) *before* normalization.
    # We replicate this exactly for v1 mode so the final FRD is identical to the paper's results.
    if frd_version == FRD_VERSION_V1:
        for idx in range(len(feature_list)):
            feats = feature_list[idx]
            # Drop rows (images) with any NaN feature value
            nan_row_mask = np.isnan(feats).any(axis=1)
            if nan_row_mask.any():
                n_dropped = int(nan_row_mask.sum())
                logging.info(
                    f"v1 compat: dropping {n_dropped} image(s) with NaN features "
                    f"from distribution {idx} ({feats.shape[0] - n_dropped} remaining)."
                )
                feats = feats[~nan_row_mask]
            # Cast to float32 (matching original v1's pandas→numpy→float32 conversion)
            feature_list[idx] = feats.astype(np.float32)

    # ── Match sample counts ──
    if match_sample_count:
        feature_list = _apply_match_sample_count(feature_list)

    mu_list = []
    sigma_list = []
    normalized_feature_list = []

    base_distribution = None
    if norm_ref == NORM_REF_JOINT:
        base_distribution = np.concatenate(feature_list, axis=0)
    elif norm_ref == NORM_REF_D1:
        base_distribution = feature_list[0]
    # NORM_REF_INDEPENDENT: base_distribution stays None → each set uses own stats

    # For v1 mode, use "raw" z-score: don't special-case std=0 and don't replace
    # NaN post-normalization, so that inf/nan values propagate to the column filter.
    # This matches the original v1 pipeline: ``(x - mean) / std`` with no guards.
    v1_zscore_compat = frd_version == FRD_VERSION_V1

    for idx, features in enumerate(feature_list):
        if norm_type == "minmax":
            normalized_features = min_max_normalize(
                features=features,
                new_min=norm_range[0],
                new_max=norm_range[1],
                feature_names=feature_names,
                base_distribution=base_distribution,
            )
        elif norm_type == "zscore":
            normalized_features = z_score_normalize(
                features=features,
                new_min=norm_range[0],
                new_max=norm_range[1],
                feature_names=feature_names,
                base_distribution=base_distribution,
                replace_nan=not v1_zscore_compat,
                handle_std_zero=not v1_zscore_compat,
            )
        else:
            raise ValueError(
                f"Normalization type '{norm_type}' is not supported. Use 'minmax' or 'zscore'."
            )
        mu_list.append(np.mean(normalized_features, axis=0))
        sigma_list.append(np.cov(normalized_features, rowvar=False))
        normalized_feature_list.append(normalized_features)

    # ── Drop NaN/Inf feature columns (v1 mode) ──
    # Original v1 drops entire feature columns that have any NaN or Inf in either
    # distribution after z-score normalization. This is necessary because D1-only
    # normalization can produce Inf when std=0 for D1 but the feature varies in D2.
    if frd_version == FRD_VERSION_V1 and len(normalized_feature_list) >= 2:
        nan_inf_mask = np.zeros(normalized_feature_list[0].shape[1], dtype=bool)
        for nf in normalized_feature_list:
            nan_inf_mask |= np.isnan(nf).any(axis=0) | np.isinf(nf).any(axis=0)
        if nan_inf_mask.any():
            n_dropped = int(nan_inf_mask.sum())
            keep = ~nan_inf_mask
            logging.info(
                f"Dropping {n_dropped} feature columns with NaN/Inf after normalization "
                f"({int(keep.sum())} remaining)."
            )
            normalized_feature_list = [nf[:, keep] for nf in normalized_feature_list]
            feature_names = [fn for fn, k in zip(feature_names, keep) if k]
            # Recompute mu/sigma after dropping
            mu_list = [np.mean(nf, axis=0) for nf in normalized_feature_list]
            sigma_list = [np.cov(nf, rowvar=False) for nf in normalized_feature_list]

    if save_features:
        for idx, normalized_features in enumerate(normalized_feature_list):
            folder_name = Path(file_lists[idx][0]).parent.stem
            unique_identifier = int(time.time())
            storage_dir = str(Path(file_lists[idx][0]).parents[1])

            csv_file_path = os.path.join(
                storage_dir,
                f"radiomics_set{idx}_results_{folder_name}_{unique_identifier}.csv",
            )
            norm_csv_file_path = os.path.join(
                storage_dir,
                f"radiomics_set{idx}_results_normalized_{folder_name}_{unique_identifier}.csv",
            )
            save_features_to_csv(
                csv_file_path,
                file_lists[idx],
                all_mask_paths[idx],
                all_radiomics_results[idx],
            )
            # Save normalized features as dicts for the normalized CSV
            norm_dicts = []
            for row_idx in range(normalized_features.shape[0]):
                norm_dicts.append(
                    {
                        fn: float(normalized_features[row_idx, col_idx])
                        for col_idx, fn in enumerate(feature_names)
                    }
                )
            norm_mask_paths = (
                all_mask_paths[idx]
                if all_mask_paths[idx]
                else [None] * len(file_lists[idx])
            )
            save_features_to_csv(
                norm_csv_file_path, file_lists[idx], norm_mask_paths, norm_dicts
            )

    return mu_list, sigma_list, normalized_feature_list, feature_names


def compute_statistics_of_paths(
    paths: list,
    norm_type: str,
    norm_range: list,
    feature_extractor,
    paths_mask: list = None,
    resize_size=None,
    verbose=False,
    save_features=False,
    norm_ref=NORM_REF_DEFAULT,
    num_workers=None,
    exclude_features=None,
    match_sample_count=False,
    frd_version=FRD_VERSION_DEFAULT,
):
    """Resolve paths (directories or .npz files) and compute feature statistics."""

    if not isinstance(paths[0], list) and paths[0].endswith(".npz"):
        with np.load(paths[0]) as f:
            mu1, sigma1 = f["mu"][:], f["sigma"][:]
        if len(paths) < 2:
            return [mu1], [sigma1], [], []
        if not isinstance(paths[1], list) and paths[1].endswith(".npz"):
            with np.load(paths[1]) as f:
                mu2, sigma2 = f["mu"][:], f["sigma"][:]
            return [mu1, mu2], [sigma1, sigma2], [], []
        else:
            raise ValueError(
                "When the first path is a .npz file, the second path must also "
                "be a .npz file, or use image directories for both paths."
            )
    else:
        file_lists = []
        mask_lists = []
        for idx, path in enumerate(paths):
            if isinstance(path, list):
                file_lists.append(path)
            else:
                path = pathlib.Path(path)
                file_lists.append(
                    sorted(
                        [
                            file
                            for ext in IMAGE_EXTENSIONS
                            for file in path.glob("*.{}".format(ext))
                        ]
                    )
                )
        if paths_mask is not None:
            for idx2, path_mask in enumerate(paths_mask):
                if path_mask is None:
                    mask_lists.append(None)
                elif isinstance(path_mask, list):
                    mask_lists.append(path_mask)
                else:
                    path_mask = pathlib.Path(path_mask)
                    mask_lists.append(
                        sorted(
                            [
                                mask
                                for ext in IMAGE_EXTENSIONS
                                for mask in path_mask.glob("*.{}".format(ext))
                            ]
                        )
                    )
            for midx, (ml, fl) in enumerate(zip(mask_lists, file_lists)):
                if ml is not None and len(ml) != len(fl):
                    logging.warning(
                        f"Distribution {midx}: Number of mask files ({len(ml)}) != "
                        f"number of images ({len(fl)}). Please verify."
                    )
        else:
            mask_lists = [None] * len(paths)
            if verbose:
                logging.debug(f"file_lists: {file_lists}")

        return calculate_feature_statistics(
            file_lists=file_lists,
            norm_type=norm_type,
            norm_range=norm_range,
            feature_extractor=feature_extractor,
            mask_lists=mask_lists,
            resize_size=resize_size,
            verbose=verbose,
            save_features=save_features,
            norm_ref=norm_ref,
            num_workers=num_workers,
            exclude_features=exclude_features,
            match_sample_count=match_sample_count,
            frd_version=frd_version,
        )


# ─────────────────────────────────────────────────────────────────────────────
#  Version-aware defaults
# ─────────────────────────────────────────────────────────────────────────────


def _resolve_defaults(
    frd_version, norm_type, norm_range, features, image_types, norm_ref=None
):
    """Resolve None args to version-specific defaults."""
    if frd_version == FRD_VERSION_V0:
        if norm_type is None:
            norm_type = V0_DEFAULT_NORM_TYPE
        if norm_range is None:
            norm_range = list(V0_DEFAULT_NORM_RANGE)
        if features is None:
            features = list(V0_DEFAULT_FEATURES)
        if norm_ref is None:
            norm_ref = V0_DEFAULT_NORM_REF
        # image_types=None means "use v0 default (Original only)" — handled in extractor
    else:  # v1
        if norm_type is None:
            norm_type = V1_DEFAULT_NORM_TYPE
        if norm_range is None:
            norm_range = list(V1_DEFAULT_NORM_RANGE)
        if norm_ref is None:
            norm_ref = V1_DEFAULT_NORM_REF
        # features=None means "use YAML defaults" for v1; user-specified overrides YAML
        # image_types=None means "use YAML defaults (Original+LoG+Wavelet)" — handled in extractor
    return norm_type, norm_range, features, image_types, norm_ref


# ─────────────────────────────────────────────────────────────────────────────
#  Main API: compute_frd
# ─────────────────────────────────────────────────────────────────────────────


def compute_frd(
    paths,
    frd_version=FRD_VERSION_DEFAULT,
    features=None,
    norm_type=None,
    norm_range=None,
    paths_masks=None,
    resize_size=None,
    verbose=False,
    save_features=False,
    norm_ref=NORM_REF_DEFAULT,
    num_workers=None,
    image_types=None,
    use_paper_log=False,
    log_sigma=None,
    config_path=None,
    bin_width=None,
    normalize_scale=None,
    voxel_array_shift=None,
    exclude_features=None,
    match_sample_count=False,
    means_only=False,
    settings_dict=None,
    interpret=False,
    interpret_dir="outputs/interpretability_visualizations",
):
    """Compute the Fréchet Radiomics Distance between two image distributions.

    This is the main entry point. Supports both FRDv0 and FRDv1 (default).
    All parameters work for both versions unless noted otherwise.

    Params:
    -- paths                : List of two paths (directories or file lists) or .npz files.
    -- frd_version          : 'v0' or 'v1' (default). Determines default feature extraction,
                              normalization, and post-processing strategy.
    -- features             : List of feature class names (e.g. ['firstorder', 'glcm']).
                              For v0: defaults to all 8 classes. For v1: None uses the
                              YAML-configured classes; if specified, overrides the YAML.
    -- norm_type            : 'minmax' or 'zscore'. Default depends on frd_version.
    -- norm_range           : [min, max] for normalization rescaling. Default depends on frd_version.
    -- paths_masks          : Optional list of two mask directory paths.
    -- resize_size          : Optional pixel resize target (int or (w,h) tuple).
    -- verbose              : Logging verbosity.
    -- save_features        : Save features to CSV (default False).
    -- norm_ref             : str, one of 'joint' (default), 'd1', or 'independent'.
    -- num_workers          : CPU workers for multiprocessing (None = auto).
    -- image_types          : List of pyradiomics image types, e.g. ['Original', 'LoG', 'Wavelet'].
    -- use_paper_log        : bool. If True, apply paper Eq. 3 log transform: FRD = log(d_F).
                              Default False uses the original code convention: FRD = log(d_F^2).
    -- log_sigma            : list of float, LoG sigma values (e.g. [2.0, 3.0, 4.0, 5.0]).
    -- config_path          : str, path to a custom pyradiomics YAML config file.
                              When provided, overrides feature_groups, image_types, log_sigma,
                              bin_width, and other extractor settings entirely.
    -- bin_width            : int, pyradiomics binWidth setting.
    -- normalize_scale      : float, pyradiomics normalizeScale setting.
    -- voxel_array_shift    : float, pyradiomics voxelArrayShift setting.
    -- exclude_features     : list of str, feature categories to exclude after extraction.
                              Options: 'textural', 'wavelet', 'firstorder'.
    -- match_sample_count   : bool, if True subsample the larger dataset to match the smaller.
    -- means_only           : bool, if True compute FRD using only mean vectors (no covariance).
    -- settings_dict        : dict, arbitrary pyradiomics settings passed directly to extractor.
    -- interpret            : bool, if True run interpretability analysis after FRD computation.
    -- interpret_dir        : str, directory for interpretability output files.

    Returns:
    -- frd_value : The computed FRD score. For v1 this is log-transformed.
    """
    if frd_version not in FRD_VERSIONS:
        raise ValueError(
            f"Unknown frd_version '{frd_version}'. Must be one of {sorted(FRD_VERSIONS)}."
        )

    norm_type, norm_range, features, image_types, norm_ref = _resolve_defaults(
        frd_version, norm_type, norm_range, features, image_types, norm_ref=norm_ref
    )

    if norm_ref not in NORM_REF_OPTIONS:
        raise ValueError(
            f"Unknown norm_ref '{norm_ref}'. Must be one of {sorted(NORM_REF_OPTIONS)}."
        )

    if norm_ref == NORM_REF_INDEPENDENT:
        warnings.warn(
            "norm_ref='independent': Each dataset's features are normalized using only "
            "their own statistics. This differs from the default joint normalization and "
            "the paper's D1-reference normalization (Eq. 3), and may reduce comparability "
            "of FRD values across experiments.",
            UserWarning,
            stacklevel=2,
        )

    _ensure_radiomics()

    if not verbose:
        logger = logging.getLogger("radiomics")
        logger.setLevel(logging.ERROR)
        setVerbosity(60)

    for p in paths:
        if not isinstance(p, list) and not os.path.exists(p):
            raise RuntimeError(
                f"Invalid path: {p}. Provide a valid directory or list of files."
            )

    if (
        norm_ref != NORM_REF_INDEPENDENT
        and not isinstance(paths[0], list)
        and paths[0].endswith(".npz")
    ):
        raise ValueError(
            f"norm_ref='{norm_ref}' is not supported with .npz files (statistics already computed). "
            "Use norm_ref='independent' or provide image paths."
        )

    # Detect 2D vs 3D for v1 config selection
    image_dim = 2  # default
    if frd_version == FRD_VERSION_V1:
        # Detect dimensionality from the first path/file
        _first_path = paths[0]
        if isinstance(_first_path, list):
            _files_for_detection = _first_path
        else:
            _first_path_obj = pathlib.Path(_first_path)
            _files_for_detection = sorted(
                [
                    f
                    for ext in IMAGE_EXTENSIONS
                    for f in _first_path_obj.glob(f"*.{ext}")
                ]
            )
        if _files_for_detection:
            image_dim = _detect_image_dimensionality(_files_for_detection)
            if verbose:
                logging.info(
                    f"Detected {image_dim}D images. Using corresponding v1 config."
                )

    feature_extractor = get_feature_extractor(
        frd_version=frd_version,
        features=features,
        image_dim=image_dim,
        image_types=image_types,
        log_sigma=log_sigma,
        config_path=config_path,
        bin_width=bin_width,
        normalize_scale=normalize_scale,
        voxel_array_shift=voxel_array_shift,
    )

    # Apply arbitrary user settings on top
    if settings_dict:
        for key, val in settings_dict.items():
            feature_extractor.settings[key] = val

    mu_list, sigma_list, normalized_feature_list, feature_names = (
        compute_statistics_of_paths(
            paths,
            norm_type,
            norm_range,
            feature_extractor,
            paths_mask=paths_masks,
            resize_size=resize_size,
            verbose=verbose,
            save_features=save_features,
            norm_ref=norm_ref,
            num_workers=num_workers,
            exclude_features=exclude_features,
            match_sample_count=match_sample_count,
            frd_version=frd_version,
        )
    )

    if verbose:
        logging.debug(f"mu_list shapes: {[m.shape for m in mu_list]}")

    frd_value = calculate_frechet_distance(
        mu_list[0],
        sigma_list[0],
        mu_list[1],
        sigma_list[1],
        means_only=means_only,
    )

    # v1 applies log transform for stability.
    if frd_version == FRD_VERSION_V1:
        if use_paper_log:
            warnings.warn(
                "use_paper_log=True: Computing FRD as log(sqrt(d_F^2)) per paper Eq. 3. "
                "This produces values that are HALF of the default (log(d_F^2)) and are "
                "NOT directly comparable to previously published FRD values or experiments "
                "that used the default setting. Only use this if you specifically need "
                "paper-formula consistency.",
                UserWarning,
                stacklevel=2,
            )
            # Paper formula: FRD = log(d_F) = log(sqrt(d_F^2)) = 0.5 * log(d_F^2)
            frd_value = np.log(np.sqrt(frd_value)) if frd_value > 0 else float("-inf")
        else:
            # Original code convention: FRD = log(d_F^2)
            frd_value = np.log(frd_value) if frd_value > 0 else float("-inf")

    print(f"FRD ({frd_version}): {frd_value}")

    # ── Interpretability analysis ──
    if interpret:
        interpret_frd(
            normalized_feature_list,
            feature_names,
            viz_dir=interpret_dir,
        )

    return frd_value


# ─────────────────────────────────────────────────────────────────────────────
#  Save stats (.npz)
# ─────────────────────────────────────────────────────────────────────────────


def save_frd_stats(
    paths,
    frd_version=FRD_VERSION_DEFAULT,
    features=None,
    norm_type=None,
    norm_range=None,
    paths_masks=None,
    resize_size=None,
    verbose=False,
    save_features=False,
    norm_ref=NORM_REF_DEFAULT,
    num_workers=None,
    image_types=None,
    use_paper_log=False,
    log_sigma=None,
    config_path=None,
    bin_width=None,
    normalize_scale=None,
    voxel_array_shift=None,
    exclude_features=None,
    match_sample_count=False,
    settings_dict=None,
):
    """Compute and save feature statistics for a single distribution to a .npz file.

    Note: use_paper_log is accepted for API consistency with compute_frd() but
    has no effect here since save_frd_stats only stores mu/sigma, not the final
    FRD score.
    """

    norm_type, norm_range, features, image_types, norm_ref = _resolve_defaults(
        frd_version, norm_type, norm_range, features, image_types, norm_ref=norm_ref
    )

    if norm_ref not in NORM_REF_OPTIONS:
        raise ValueError(
            f"Unknown norm_ref '{norm_ref}'. Must be one of {sorted(NORM_REF_OPTIONS)}."
        )

    if not isinstance(paths[0], list) and not os.path.exists(paths[0]):
        raise RuntimeError(f"Invalid input path: {paths[0]}")
    if os.path.exists(paths[1]):
        raise RuntimeError(f"Output .npz file already exists: {paths[1]}")
    elif not paths[1].endswith(".npz"):
        logging.warning(
            f"Output path '{paths[1]}' does not have .npz extension. Continuing anyway."
        )

    # Detect 2D vs 3D
    image_dim = 2
    if frd_version == FRD_VERSION_V1:
        _first_path = paths[0]
        if isinstance(_first_path, list):
            _files_for_detection = _first_path
        else:
            _first_path_obj = pathlib.Path(_first_path)
            _files_for_detection = sorted(
                [
                    f
                    for ext in IMAGE_EXTENSIONS
                    for f in _first_path_obj.glob(f"*.{ext}")
                ]
            )
        if _files_for_detection:
            image_dim = _detect_image_dimensionality(_files_for_detection)

    feature_extractor = get_feature_extractor(
        frd_version=frd_version,
        features=features,
        image_dim=image_dim,
        image_types=image_types,
        log_sigma=log_sigma,
        config_path=config_path,
        bin_width=bin_width,
        normalize_scale=normalize_scale,
        voxel_array_shift=voxel_array_shift,
    )

    # Apply arbitrary user settings on top
    if settings_dict:
        for key, val in settings_dict.items():
            feature_extractor.settings[key] = val

    if verbose:
        logging.info(f"Computing statistics for {paths[0]}")

    mu_list, sigma_list, _, _ = compute_statistics_of_paths(
        [paths[0]],
        norm_type=norm_type,
        norm_range=norm_range,
        feature_extractor=feature_extractor,
        paths_mask=None if paths_masks is None else [paths_masks[0]],
        resize_size=resize_size,
        verbose=verbose,
        save_features=save_features,
        norm_ref=norm_ref,
        num_workers=num_workers,
        exclude_features=exclude_features,
        match_sample_count=match_sample_count,
        frd_version=frd_version,
    )

    np.savez_compressed(paths[1], mu=mu_list[0], sigma=sigma_list[0])


# ─────────────────────────────────────────────────────────────────────────────
#  main() for CLI usage
# ─────────────────────────────────────────────────────────────────────────────


def main():
    args = parse_args()

    # ── Handle OOD subcommand ──
    if getattr(args, "subcommand", None) == "ood":
        verbose = args.verbose
        frd_version = args.frd_version
        norm_type = args.norm_type
        norm_range = args.norm_range
        features = args.feature_groups
        image_types = args.image_types

        norm_ref = args.norm_ref
        norm_type, norm_range, features, image_types, norm_ref = _resolve_defaults(
            frd_version, norm_type, norm_range, features, image_types, norm_ref=norm_ref
        )

        _ensure_radiomics()

        if verbose:
            logging.basicConfig(level=logging.INFO)
        else:
            logger = logging.getLogger("radiomics")
            logger.setLevel(logging.ERROR)
            setVerbosity(60)

        # Detect dimensionality
        image_dim = 2
        if frd_version == FRD_VERSION_V1:
            _first_path = args.paths[0]
            if isinstance(_first_path, list):
                _files_for_detection = _first_path
            else:
                _first_path_obj = pathlib.Path(_first_path)
                _files_for_detection = sorted(
                    [
                        f
                        for ext in IMAGE_EXTENSIONS
                        for f in _first_path_obj.glob(f"*.{ext}")
                    ]
                )
            if _files_for_detection:
                image_dim = _detect_image_dimensionality(_files_for_detection)

        feature_extractor = get_feature_extractor(
            frd_version=frd_version,
            features=features,
            image_dim=image_dim,
            image_types=image_types,
            log_sigma=args.log_sigma,
            config_path=args.config_path,
            bin_width=args.bin_width,
            normalize_scale=args.normalize_scale,
            voxel_array_shift=args.voxel_array_shift,
        )

        _, _, normalized_feature_list, _ = compute_statistics_of_paths(
            args.paths,
            norm_type,
            norm_range,
            feature_extractor,
            paths_mask=args.paths_masks,
            resize_size=args.resize_size,
            verbose=verbose,
            save_features=False,
            norm_ref=norm_ref,
            num_workers=args.num_workers,
            exclude_features=args.exclude_features,
            match_sample_count=args.match_sample_count,
            frd_version=frd_version,
        )

        # Gather test filenames for CSV output
        test_filenames = None
        test_path = args.paths[1]
        if isinstance(test_path, list):
            test_filenames = [str(f) for f in test_path]
        else:
            test_path_obj = pathlib.Path(test_path)
            test_files = sorted(
                [f for ext in IMAGE_EXTENSIONS for f in test_path_obj.glob(f"*.{ext}")]
            )
            test_filenames = [f.name for f in test_files]

        ood_results = detect_ood(
            normalized_feature_list,
            detection_type=args.detection_type,
            val_frac=args.val_frac,
            use_val_set=args.use_val_set,
            id_dist_assumption=args.id_dist_assumption,
            output_dir=args.output_dir,
            seed=args.seed,
            filenames=test_filenames,
        )
        return

    # ── Standard FRD computation ──
    verbose = args.verbose
    frd_version = args.frd_version
    norm_type = args.norm_type
    norm_range = args.norm_range
    features = args.feature_groups
    image_types = args.image_types
    use_paper_log = args.use_paper_log

    # Resolve defaults based on version
    norm_ref = args.norm_ref
    norm_type, norm_range, features, image_types, norm_ref = _resolve_defaults(
        frd_version, norm_type, norm_range, features, image_types, norm_ref=norm_ref
    )

    _ensure_radiomics()

    if verbose:
        logging.basicConfig(level=logging.INFO)
        logging.info(args)
    else:
        logger = logging.getLogger("radiomics")
        logger.setLevel(logging.ERROR)
        setVerbosity(60)

    # Shared new-param kwargs
    _new_params = dict(
        log_sigma=getattr(args, "log_sigma", None),
        config_path=getattr(args, "config_path", None),
        bin_width=getattr(args, "bin_width", None),
        normalize_scale=getattr(args, "normalize_scale", None),
        voxel_array_shift=getattr(args, "voxel_array_shift", None),
        exclude_features=getattr(args, "exclude_features", None),
        match_sample_count=getattr(args, "match_sample_count", False),
    )

    if args.save_stats:
        save_frd_stats(
            args.paths,
            frd_version=frd_version,
            features=features,
            norm_type=norm_type,
            norm_range=norm_range,
            paths_masks=args.paths_masks,
            resize_size=args.resize_size,
            verbose=verbose,
            save_features=args.save_features,
            num_workers=args.num_workers,
            norm_ref=args.norm_ref,
            image_types=image_types,
            use_paper_log=use_paper_log,
            **_new_params,
        )
        return

    frd_value = compute_frd(
        args.paths,
        frd_version=frd_version,
        features=features,
        norm_type=norm_type,
        norm_range=norm_range,
        paths_masks=args.paths_masks,
        resize_size=args.resize_size,
        verbose=verbose,
        save_features=args.save_features,
        norm_ref=args.norm_ref,
        num_workers=args.num_workers,
        image_types=image_types,
        use_paper_log=use_paper_log,
        means_only=getattr(args, "means_only", False),
        interpret=getattr(args, "interpret", False),
        interpret_dir=getattr(
            args, "interpret_dir", "outputs/interpretability_visualizations"
        ),
        **_new_params,
    )

    logging.info(
        f"FRD ({frd_version}): {frd_value}. "
        f"norm_type={norm_type}, norm_range={norm_range}, "
        f"norm_ref={args.norm_ref}, masks={args.paths_masks}, "
        f"resize={args.resize_size}."
    )


if __name__ == "__main__":
    main()
